# -*- coding: utf-8 -*-
"""Trabajo 7 Fundamentos de la programacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tasyRhctjbX3_uMt5EkigNuzsNQlfQ81
"""

contraseña = "Chesire3110"

if len(contraseña) >= 8 and any(c.isupper() for c in contraseña) and any(c.isdigit() for c in contraseña):
    print("Valido")
else:
    print("Otra vez")

unidades = 22.00

if unidades <= 100:
    impuesto = unidades * 0.10
elif unidades <= 200:
    impuesto = unidades * 0.15
else:
    impuesto = unidades * 0.20

print(f"Impuesto aplicado: ${impuesto:.2f}")

total = float(input("Total de la cuenta: $"))
porcentaje = float(input("Porcentaje de propina: "))
propina = total * porcentaje / 100
total_pagar = total + propina
print(f"Total a pagar: ${total_pagar:.2f}")

nombre = "Gustavo Javier Cardona Gonzalez"
partes = nombre.split()
correo = f"{partes[0].lower()}.{partes[2].lower()}@keyinstitute.edu.sv"
print(f"Tu correo es: {correo}")